/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.UCManageDish;

import Bean.DishBean;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DishListFrm extends javax.swing.JFrame {
    private ArrayList<DishBean> list;
    private DefaultTableModel model;

    /**
     * Creates new form DishListDrm
     */
    public DishListFrm(ArrayList<DishBean> list) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.getContentPane().setBackground(Color.pink);
        this.list=list;
        model = (DefaultTableModel) tblDishList.getModel();
        showList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDishList = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDishList.setBackground(new java.awt.Color(255, 204, 204));
        tblDishList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Name", "Discrip", "price"
            }
        ));
        jScrollPane1.setViewportView(tblDishList);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnEdit)
                .addGap(185, 185, 185)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tblDishList.getSelectedRow();
        String ID = tblDishList.getValueAt(row, 0).toString().trim();
        String type = tblDishList.getValueAt(row, 1).toString().trim();
        String name = tblDishList.getValueAt(row, 2).toString().trim();
        String discrip = tblDishList.getValueAt(row, 3).toString().trim();
        String price = tblDishList.getValueAt(row, 4).toString().trim();
        
        int IDn = Integer.parseInt(ID);
        float pricen = Float.parseFloat(price);
        DishBean dish = new DishBean(IDn, type, name, discrip, pricen);
        new editDishFrm(dish);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          int row = tblDishList.getSelectedRow();
        String ID = tblDishList.getValueAt(row, 0).toString().trim();
        String type = tblDishList.getValueAt(row, 1).toString().trim();
        String name = tblDishList.getValueAt(row, 2).toString().trim();
        String discrip = tblDishList.getValueAt(row, 3).toString().trim();
        String price = tblDishList.getValueAt(row, 4).toString().trim();
        
        int IDn = Integer.parseInt(ID);
        float pricen = Float.parseFloat(price);
        DishBean dish = new DishBean(IDn, type, name, discrip, pricen);
        new DeleteDishFrm(dish);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void showList() {
        model.setRowCount(0);
        for (DishBean d : list) {
        model.addRow(new Object[]{d.getID(),d.getType(),d.getName(),d.getDiscrip(),d.getPrice()});
    }

    /**
     * @param args the command line arguments
     */

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDishList;
    // End of variables declaration//GEN-END:variables
}
